// Index of brandon-fryslie's deployed GitHub Pages sites.
// Loads sites.json (committed snapshot, regenerated by ./generate.sh).

const $ = (sel) => document.querySelector(sel);

const LANG_COLORS = {
  Python: '#3572A5',
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  Go: '#00ADD8',
  Shell: '#89e051',
  Ruby: '#701516',
  CoffeeScript: '#244776',
  CSS: '#663399',
  HTML: '#e34c26',
  C: '#555555',
  PHP: '#4F5D95',
  Kotlin: '#A97BFF',
  Clojure: '#db5855',
  Groovy: '#4298b8',
  HCL: '#844FBA',
};

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function relTime(iso) {
  const then = new Date(iso);
  if (isNaN(then.getTime())) return '';
  const days = Math.floor((Date.now() - then.getTime()) / 86400000);
  if (days < 1) return 'today';
  if (days < 2) return 'yesterday';
  if (days < 30) return `${days}d ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

// Strip the "https://" prefix and any trailing slash for compact display
function displayUrl(url) {
  return url.replace(/^https?:\/\//, '').replace(/\/$/, '');
}

function renderHeader(user) {
  if (user.avatar_url) {
    $('#avatar').src = user.avatar_url;
    $('#avatar').alt = user.name || user.login || '';
  }
  $('#name').textContent = user.name || user.login || '';
  $('#bio').textContent = user.bio || '';
  $('#profile-link').href = user.html_url || `https://github.com/${user.login}`;
}

function renderStats(sites) {
  const total = sites.length;
  const cutoff = new Date(Date.now() - 90 * 86400 * 1000).toISOString();
  const recent = sites.filter(s => s.pushed_at > cutoff).length;

  $('#stat-strip').innerHTML = `
    <span><strong>${total}</strong> deployed sites</span>
    <span><strong>${recent}</strong> updated <span style="opacity:0.6">in last 90d</span></span>
    <span style="opacity:0.6">all deploys via <a href="https://github.com/brandon-fryslie/gh-pages-multiplexer" target="_blank" rel="noopener" style="color:var(--accent);">gh-pages-multiplexer</a></span>
  `;
}

function renderSiteCard(s) {
  const langColor = LANG_COLORS[s.language] || '#888';
  const langPart = s.language
    ? `<span class="lang"><span class="lang-dot" style="background:${langColor}"></span>${escapeHtml(s.language)}</span>`
    : '';

  const desc = s.description
    ? escapeHtml(s.description)
    : '<em class="no-desc">(no description)</em>';

  return `<article class="site-card">
    <header class="site-card-head">
      <h3 class="site-name">${escapeHtml(s.name)}</h3>
    </header>

    <p class="site-desc">${desc}</p>

    <a class="site-url" href="${escapeHtml(s.pages_url)}" target="_blank" rel="noopener">
      <span class="visit-arrow">→</span>
      <span class="url-text">${escapeHtml(displayUrl(s.pages_url))}</span>
    </a>

    <footer class="site-meta">
      ${langPart}
      <span>updated ${relTime(s.pushed_at)}</span>
      <a class="source-link" href="${escapeHtml(s.repo_url)}" target="_blank" rel="noopener">source ↗</a>
    </footer>
  </article>`;
}

async function init() {
  let data;
  try {
    const res = await fetch('sites.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    data = await res.json();
  } catch (e) {
    console.error('Failed to load sites.json:', e);
    $('#sites-grid').innerHTML =
      '<p style="color:var(--text-dim);">Failed to load sites index. Run <code>./generate.sh</code> and reload.</p>';
    return;
  }

  // sites.json is hand-curated; no need to filter the self-link out
  // (the index doesn't list itself by convention).
  const sites = data.sites || [];

  renderHeader(data.user || {});
  renderStats(sites);

  $('#sites-grid').innerHTML = sites.length
    ? sites.map(renderSiteCard).join('')
    : '<p style="color:var(--text-dim);">No deployed sites listed yet.</p>';

  $('#result-count').textContent = `${sites.length} sites`;
  $('#generated-at').textContent = 'hand-curated index';
}

init();
