// brandon-fryslie.github.io root index.
// Loads projects.json (committed alongside; regenerated by ./generate.sh)
// and renders a filterable grid of all non-fork repos. Pure data-driven —
// no GitHub API calls at runtime so anonymous viewers don't hit rate limits.

const $ = (sel) => document.querySelector(sel);

// Subset of GitHub's official linguist colors — one per language we own.
// Add to this list when generate.sh starts surfacing a new language.
const LANG_COLORS = {
  Python: '#3572A5',
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  Go: '#00ADD8',
  Shell: '#89e051',
  Ruby: '#701516',
  CoffeeScript: '#244776',
  CSS: '#663399',
  HTML: '#e34c26',
  C: '#555555',
  PHP: '#4F5D95',
  Kotlin: '#A97BFF',
  Clojure: '#db5855',
  Groovy: '#4298b8',
  HCL: '#844FBA',
  Rust: '#dea584',
  Lua: '#000080',
  Vim: '#199f4b',
  WGSL: '#1a5490',
};

const state = {
  data: null,
  search: '',
  language: null,    // null = "All"
};

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function relTime(iso) {
  const then = new Date(iso);
  if (isNaN(then.getTime())) return '';
  const days = Math.floor((Date.now() - then.getTime()) / 86400000);
  if (days < 1) return 'today';
  if (days < 2) return 'yesterday';
  if (days < 30) return `${days}d ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  const y = Math.floor(days / 365);
  return `${y}y ago`;
}

function renderHeader(user) {
  if (user.avatar_url) {
    $('#avatar').src = user.avatar_url;
    $('#avatar').alt = user.name || user.login || '';
  }
  $('#name').textContent = user.name || user.login || '';
  $('#bio').textContent = user.bio || '';
  $('#profile-link').href = user.html_url || `https://github.com/${user.login}`;
}

function renderStats(data) {
  const total = data.repos.length;
  const cutoff = new Date(Date.now() - 90 * 86400 * 1000).toISOString();
  const active = data.repos.filter(r => r.pushed_at > cutoff).length;
  const langs = {};
  data.repos.forEach(r => { if (r.language) langs[r.language] = (langs[r.language] || 0) + 1; });
  const topLang = Object.entries(langs).sort((a, b) => b[1] - a[1])[0]?.[0] || '—';
  const totalStars = data.repos.reduce((s, r) => s + (r.stars || 0), 0);

  $('#stat-strip').innerHTML = `
    <span><strong>${total}</strong> repositories</span>
    <span><strong>${active}</strong> active <span style="opacity:0.6">in last 90d</span></span>
    <span>top language: <strong>${escapeHtml(topLang)}</strong></span>
    <span>total stars: <strong>${totalStars}</strong></span>
  `;
}

function renderLangChips(data) {
  const counts = {};
  data.repos.forEach(r => { if (r.language) counts[r.language] = (counts[r.language] || 0) + 1; });
  const sorted = Object.entries(counts).sort((a, b) => b[1] - a[1]);

  const allChip = `<button type="button" class="lang-chip active" data-lang="">All <span class="count">${data.repos.length}</span></button>`;
  const chips = sorted.map(([lang, count]) =>
    `<button type="button" class="lang-chip" data-lang="${escapeHtml(lang)}">${escapeHtml(lang)} <span class="count">${count}</span></button>`
  );
  $('#lang-chips').innerHTML = [allChip, ...chips].join('');

  $('#lang-chips').addEventListener('click', (ev) => {
    const btn = ev.target.closest('.lang-chip');
    if (!btn) return;
    state.language = btn.dataset.lang || null;
    document.querySelectorAll('.lang-chip').forEach(c => c.classList.toggle('active', c === btn));
    renderRepos();
  });
}

function renderRepoCard(r) {
  const langColor = LANG_COLORS[r.language] || '#888';
  const langPart = r.language
    ? `<span class="lang"><span class="lang-dot" style="background:${langColor}"></span>${escapeHtml(r.language)}</span>`
    : '';
  const starsPart = (r.stars && r.stars > 0) ? `<span>★ ${r.stars}</span>` : '';
  const archivedBadge = r.archived ? '<span class="archived-badge">archived</span>' : '';
  const desc = r.description
    ? escapeHtml(r.description)
    : '<em>(no description)</em>';

  return `<div class="repo-card">
    <div class="repo-card-header">
      <h3><a href="${escapeHtml(r.url)}" target="_blank" rel="noopener">${escapeHtml(r.name)}</a></h3>
      ${archivedBadge}
    </div>
    <p class="description">${desc}</p>
    <div class="meta">
      ${langPart}
      ${starsPart}
      <span>updated ${relTime(r.pushed_at)}</span>
    </div>
  </div>`;
}

function renderRepos() {
  if (!state.data) return;
  const q = state.search.trim().toLowerCase();
  const filtered = state.data.repos.filter(r => {
    if (state.language && r.language !== state.language) return false;
    if (q) {
      const haystack = [
        r.name,
        r.description || '',
        (r.topics || []).join(' '),
        r.language || ''
      ].join(' ').toLowerCase();
      if (!haystack.includes(q)) return false;
    }
    return true;
  });

  $('#repos-grid').innerHTML = filtered.length
    ? filtered.map(renderRepoCard).join('')
    : '<p style="color:var(--text-faint); grid-column: 1 / -1;">No repos match.</p>';

  const langSuffix = state.language ? ` · language: ${state.language}` : '';
  const searchSuffix = q ? ` · matching "${q}"` : '';
  $('#result-count').textContent =
    `showing ${filtered.length} of ${state.data.repos.length} repos${langSuffix}${searchSuffix}`;
}

async function init() {
  $('#search').addEventListener('input', (e) => {
    state.search = e.target.value;
    renderRepos();
  });

  try {
    const res = await fetch('projects.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    state.data = data;

    renderHeader(data.user || {});
    renderStats(data);
    renderLangChips(data);
    renderRepos();

    if (data.generated_at) {
      $('#generated-at').textContent = `index regenerated ${relTime(data.generated_at)}`;
    }
  } catch (e) {
    console.error('Failed to load projects.json:', e);
    $('#repos-grid').innerHTML =
      '<p style="color:var(--text-dim);">Failed to load projects index. Run <code>./generate.sh</code> and reload.</p>';
  }
}

init();
